### ISSUE TITLE
Appear to be missing payload.tgz

### ISSUE THREAD

**Issue by fss-itsupport** [rssor/fs_xgspon_mod#10]
Hi
Running on Windows, following the install steps, the program errors on
[+] Stick retrieved payload configuration
192.168.100.1 - - [25/Aug/2024 15:59:42] code 404, message File not found
192.168.100.1 - - [25/Aug/2024 15:59:42] "GET /payload.tgz HTTP/1.1" 404 -

Searching for payload.tgz it seems that isnt found or ever created in the script, how do I solve this?
Thanks
John

**Comment by rssor** [comment]
Sounds like you cloned the repo rather than downloading the prebuilt release. You want [fs_xgspon_mod_release.tgz](https://github.com/rssor/fs_xgspon_mod/releases/download/v1.3/fs_xgspon_mod_release.tgz) from the releases page.

**Comment by fss-itsupport** [comment]
Thanks, I had indeed cloned the repo. Next task is to work out what settings to use for VirginMedia Hub5x
