### ISSUE TITLE
Error with KPN

### ISSUE THREAD

**Issue by infernix** [rssor/fs_xgspon_mod#6]
Just applied new KPN fix. Throws what looks like a cosmetic error:

**./fs_xgspon_mod.py install GPONXXXXXXXX kpn**
```
/home/gerben/src/fs_xgspon_mod/./fs_xgspon_mod.py:5: DeprecationWarning: 'telnetlib' is deprecated and slated for removal in Python 3.13
  from telnetlib import Telnet
[!] To make the ONU work on this ISP's network, just an ETH UNI slot override is needed
[!] Performing a slot override does not require any dangerous payloads to be applied
[!] However, you can also choose to go ahead and install the full modification
[!] When in doubt, you should probably try the less invasive (o)verride option first
Choose either (o)verride or (i)nstall: o
[+] Telnet connection established, login successful
[+] Ethernet port slot override applied -- press enter to reboot the ONU!
reboot

#ONT/system/shell>*** Connection closed by remote host ***
[+] Generated payload configuration:
Traceback (most recent call last):
  File "/home/gerben/src/fs_xgspon_mod/./fs_xgspon_mod.py", line 841, in <module>
    args.func(args)
  File "/home/gerben/src/fs_xgspon_mod/./fs_xgspon_mod.py", line 575, in install
    for line in settings.config.split("\n"):
                ^^^^^^^^^^^^^^^
AttributeError: 'KPN' object has no attribute 'config'
```

**Comment by rssor** [comment]
I think I see the issue, I'll sort it out in a few hours.

**Comment by rssor** [comment]
Until then, try just using the `overrideslot` command directly.

**Comment by infernix** [comment]
I think it is, but even still, after applying the mod I can't connect to it any longer. Obviously I could connect fine before, so this isn't a link light issue I think.

Any chance it didn't put `1` for the 10G slot port, but some text string?

**Comment by rssor** [comment]
@arpiecodes Wondering if the way it's working by passing args instead of a settings object from install is actually causing it to write `None` -- did you test use of the `install` command and allowing it to override?

**Comment by rssor** [comment]
> I think it is, but even still, after applying the mod I can't connect to it any longer. Obviously I could connect fine before, so this isn't a link light issue I think.
> 
> Any chance it didn't put `1` for the 10G slot port, but some text string?

It seems quite possible that it would have written ETH10GESLOT=None

**Comment by rssor** [comment]
Invoking the `overrideslot` command looks to be fine, but when `install` prompts and then calls `overrideslot` I think it actually bricks the device. :(

Yanked the release, cutting out the command-switching behavior.

**Comment by infernix** [comment]
And here i thought I'd be saving time vs doing it by hand :|

Any suggestions on unbricking?

**Comment by rssor** [comment]
> And here i thought I'd be saving time vs doing it by hand :|
> 
> Any suggestions on unbricking?

It will require UART access sadly. As soon as it starts it would be a race to get into the CLI, run `/system/misc/stopreboot` just in case it's panicing during boot and from there you should have time to remove `/mnt/rwdir/sys.cfg` -- if it's not getting far enough for that even, it would involve lifting the flash off and deleting it from the userdata partition directly.

**Comment by rssor** [comment]
Thank you for catching this and providing enough info to track that down quickly. That backtrace was enough to figure out everything that had happened and then figure out what slipped through.
