### ISSUE TITLE
Non-Matching S/N digits

### ISSUE THREAD

**Issue by AddictedCoins** [rssor/fs_xgspon_mod#9]
The FS.com XGSPON ONU device only has 11 digits of serial number, but the frontier ONU has 12 digits of serial number. Would this be a problem when running the script? And will it actually be effective in replacing the ISP provided ONU?

**Comment by mike-code** [comment]
I second that. I got device with G{yy}{m?}{7 digits} S/N on the sticker

**Comment by rssor** [comment]
The serial number on the label is NOT the GPON serial you need. If you are unable to get them to correctly give you the serial number presented to the OLT by the stick you need to use the brute force method from a linux machine.

See https://github.com/rssor/fs_xgspon_mod#cig-backdoor-brute-force-linux-only
